; Tox configuration file - http://tox.readthedocs.io/en/latest/config.html
[tox]
envlist = py{39}


[testenv]
deps =
    -rrequirements/test.txt

commands = py.test {posargs:--cov copiere --cov tests --cov-report term-missing --cov-report html --cov-report xml:coverage.xml}
usedevelop = True

[pytest]
doctest_optionflags = ELLIPSIS
testpaths = tests/
